name: 'dbt_personal'
version: '1.0.0'
config-version: 2

profile: 'docker'

model-paths: ["models", "functions"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_personal:
    functions:
      +materialized: function

    relations:
      +materialized: table
      +pre_hook:
        - "select http_set_curlopt('CURLOPT_TIMEOUT', '20')"
        - "select http_set_curlopt('CURLOPT_TCP_KEEPALIVE', '20')"

