version: '3.1'

services:
  db:
    build: db
    restart: always
    ports:
    - 5432:5432

    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    - JIRA_CONFIG
    - GMAIL_CONFIG

    command: [
      postgres,
      -c, "dbt_personal.jira_config=${JIRA_CONFIG}",
      -c, "dbt_personal.gmail_config=${GMAIL_CONFIG}",
    ]
